course:
  property: Course Profile Dev

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:coursesDb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: root
    password: 280101
  h2:
    console:
      enabled: true
      settings:
        trace: false
        web-allow-others: true
  jpa:
    hibernate:
      ddl-auto: create
    open-in-view: false
    show-sql: true